# Site settings
author: Pierre-Olivier Ariston
title: Data Science and me.
header-img: img/home-bg.png
email: poariston@gmail.com
copyright_name: Pierre-Olivier Ariston
description: > # this means to ignore newlines until "baseurl:"
  2019 and beyond.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  poariston

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
